Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -102,11 +102,22 @@ performance_job:
   services:
     - docker:dind
   variables:
-    URL: http://$PLAYWD-8080.direct.labs.play-with-docker.com/
+    URL: http://ip172-18-0-22-d0kcqvq91nsg00cshs70-8080.direct.labs.play-with-docker.com
     DOCKER_HOST: tcp://docker:2375
   script:
     - apk add --no-cache curl docker-cli
-    - x=1; while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://$PLAYWD-8080.direct.labs.play-with-docker.com/)" != "200" || $x -le 60 ]]; do sleep 5; echo $(( x++ )); done || false
+    - |
+      x=1
+      until curl -s -o /dev/null -w "%{http_code}" "$URL" | grep -q "200" || [ $x -gt 60 ]; do
+        echo "Waiting for app... attempt $x"
+        sleep 5
+        x=$(( x + 1 ))
+      done
+
+      if [ $x -gt 60 ]; then
+        echo "Application failed to start after waiting"
+        exit 1
+      fi
     - mkdir gitlab-exporter
     - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
     - mkdir sitespeed-results
@@ -117,6 +128,7 @@ performance_job:
       - sitespeed-results/
     reports:
       performance: performance.json
+
 container_scanning:
   stage: security
   image:
